function [fitresult, gof] = freeRelaseEst(t, freeRelaseSample)
%CREATEFIT(T,D)
%  Create a fit.
%  Ottiene i parametri:
%  - rhoMec := attrito vischioso PURAMENTE MECCANICO (Aria, ingranaggi, ecc..)
%  - uDym := Attrito dinamico costante
%  - vMax := Velocità di partenza ( dovrebbe essere simile alla velMax)
%  Data for 'discesa' fit:
%      X Input : t
%      Y Output: d
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jan-2020 10:07:58


%% Fit: 'discesa'.
[xData, yData] = prepareCurveData( t, freeRelaseSample );

% Set up fittype and options.
ft = fittype( 'vMax*exp(-rhoMec*x)+uDym*x', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf];
opts.StartPoint = [0.1626 0.7094 0.7547];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'discesa' );
% h = plot( fitresult, xData, yData );
% legend( h, 'd vs. t', 'discesa', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 't', 'Interpreter', 'none' );
% ylabel( 'd', 'Interpreter', 'none' );
% grid on


