function test = importTest(filename, dataLines, freqClock)
%IMPORTFILE Import data from a text file
%  TEST02552MS1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  TEST02552MS1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  test02552ms1 = importfile("/home/alfyhack/Documenti/mv-Project/02_SystemAnalysis/03_EstimationScript/MotorTF/SpeedData/testBench/test0-255_2ms.dat", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Feb-2020 11:47:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end
if nargin < 3
    freqClock = 16e6;   %Mhz
end

%% Setup the Import Options Settings
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [3, 3];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["dt", "OCR2A", "Prescaler"];
opts.SelectedVariableNames = ["dt", "OCR2A", "Prescaler"];
opts.VariableTypes = ["double", "double", "double"];
% opts = setvaropts(opts, 3, "WhitespaceRule", "preserve");
% opts = setvaropts(opts, 3, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the Setting
setting = readtable(filename, opts);

%% Setup the Import Options Datas
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["PWM", "mStep", "mVel", "mAcc"];
opts.VariableTypes = ["double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
test = readtable(filename, opts);

%% Extend table with time
dt = setting.OCR2A * 1/freqClock * setting.Prescaler;
Time = (0:dt:dt*(height(test)-1))';
time = table(Time);

test = [test time];

end